-- ============================================================
-- 秋招 Tracker V3 - Supabase 数据库升级
-- 可以直接在 Supabase Dashboard -> SQL Editor 中执行。
-- ============================================================

-- 1. 用户主数据：每个登录用户一行 JSON。
create table if not exists public.user_data (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.user_data enable row level security;

grant usage on schema public to authenticated;
grant select, insert, update, delete on table public.user_data to authenticated;
revoke all on table public.user_data from anon;

drop policy if exists "Users can read own tracker data" on public.user_data;
drop policy if exists "Users can insert own tracker data" on public.user_data;
drop policy if exists "Users can update own tracker data" on public.user_data;
drop policy if exists "Users can delete own tracker data" on public.user_data;

create policy "Users can read own tracker data"
on public.user_data
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own tracker data"
on public.user_data
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update own tracker data"
on public.user_data
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own tracker data"
on public.user_data
for delete
to authenticated
using (auth.uid() = user_id);

create index if not exists user_data_updated_at_idx
on public.user_data(updated_at desc);

-- 2. 邮件提醒发送日志。
-- Edge Function 使用后台 Secret key 写入；用户本人只能读取自己的发送记录。
create table if not exists public.email_reminder_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reminder_id text not null,
  notify_at timestamptz not null,
  status text not null default 'pending'
    check (status in ('pending', 'sent', 'failed')),
  provider_id text,
  attempted_at timestamptz not null default now(),
  sent_at timestamptz,
  error text,
  unique(user_id, reminder_id, notify_at)
);

alter table public.email_reminder_log enable row level security;

grant select on table public.email_reminder_log to authenticated;
revoke insert, update, delete on table public.email_reminder_log from authenticated;
revoke all on table public.email_reminder_log from anon;

drop policy if exists "Users can read own reminder logs" on public.email_reminder_log;

create policy "Users can read own reminder logs"
on public.email_reminder_log
for select
to authenticated
using (auth.uid() = user_id);

create index if not exists email_reminder_log_user_idx
on public.email_reminder_log(user_id, attempted_at desc);

create index if not exists email_reminder_log_notify_idx
on public.email_reminder_log(notify_at desc);
